# Generated by Django 5.2 on 2025-10-28 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centrosterapeuticos',
            fields=[
                ('id_centroterapeutico', models.IntegerField(db_column='ID_CentroTerapeutico', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
            ],
            options={
                'db_table': 'centrosterapeuticos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallepagos',
            fields=[
                ('codigo_pago', models.IntegerField(db_column='Codigo_Pago', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=0, max_digits=10, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=400, null=True)),
            ],
            options={
                'db_table': 'detallepagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id_especialidades', models.IntegerField(db_column='id_Especialidades', primary_key=True, serialize=False)),
                ('id_especialista', models.IntegerField()),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('matricula', models.IntegerField(blank=True, db_column='Matricula', null=True)),
            ],
            options={
                'db_table': 'especialidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialistas',
            fields=[
                ('id_especialistas', models.IntegerField(db_column='ID_Especialistas', primary_key=True, serialize=False)),
                ('id_especialidad_especialista', models.CharField(blank=True, max_length=45, null=True)),
                ('dni', models.IntegerField(blank=True, db_column='DNI', null=True)),
                ('matricula', models.IntegerField(blank=True, db_column='Matricula', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
            ],
            options={
                'db_table': 'especialistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialPaciente',
            fields=[
                ('nro_historia_paciente', models.IntegerField(db_column='Nro_Historia_paciente', primary_key=True, serialize=False)),
                ('antecedentes', models.CharField(blank=True, db_column='Antecedentes', max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=500, null=True)),
            ],
            options={
                'db_table': 'historial_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horariosespecialistas',
            fields=[
                ('id_horariosespecialistas', models.IntegerField(db_column='ID_HorariosEspecialistas', primary_key=True, serialize=False)),
                ('id_especialistas', models.CharField(blank=True, max_length=100, null=True)),
                ('horarioinicio', models.TimeField(blank=True, db_column='HorarioInicio', null=True)),
                ('horariofin', models.TimeField(blank=True, db_column='HorarioFin', null=True)),
                ('id_especialista', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horariosespecialistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObrasSociales',
            fields=[
                ('id_os', models.IntegerField(db_column='ID_OS', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
            ],
            options={
                'db_table': 'obras_sociales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('nro_pago', models.IntegerField(db_column='Nro_Pago', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, db_column='Monto', decimal_places=0, max_digits=10, null=True)),
                ('descuentos', models.DecimalField(blank=True, db_column='Descuentos', decimal_places=0, max_digits=10, null=True)),
                ('forma_pago', models.CharField(blank=True, db_column='Forma_Pago', max_length=45, null=True)),
                ('fecha_pago', models.DateField(blank=True, db_column='Fecha_Pago', null=True)),
                ('estado_pago', models.CharField(blank=True, db_column='Estado_Pago', max_length=45, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=500, null=True)),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('nro_turno', models.IntegerField(db_column='Nro_Turno', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=45, null=True)),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('dni_paciente', models.IntegerField(db_column='DNI_paciente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=45, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='EstadoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pacientes')),
            ],
            options={
                'db_table': 'entrevista',
            },
        ),
    ]
