# Generated by Django 5.2.7 on 2025-11-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contacto_testimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='testimonios/'),
        ),
    ]
