# Generated by Django 5.2.7 on 2025-11-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testimonio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='nombre_publico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre visible (ej: Mamá de Lucía)'),
        ),
    ]
