# Generated by Django 5.2.7 on 2025-11-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testimonio_nombre_publico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonio',
            name='nombre_publico',
        ),
        migrations.AddField(
            model_name='testimonio',
            name='relacion',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Tu relación con el niño/a (ejemplo: Mamá de Mateo, Tutor de Ana)'),
            preserve_default=False,
        ),
    ]
